name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.6'
      - name: Build
        run: go build -o ytmusicrpc.exe cmd/ytmusicrpc/main.go
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ytmusicrpc.exe
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: YoutubeMusicDiscordRichPresence2024SuperPuperShitCode
          path: ytmusicrpc.exe
          compression-level: 9
